services:
  - type: web
    name: your-app-name
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: host
        value: localhost
      - key: user
        value: root
      - key: password
        value: 
      - key: database
        value: chroma_spark
    autoDeploy: true
